### ISSUE TITLE
How does this compare to using jsom directly with unexpected?

### ISSUE THREAD

**Issue by faceyspacey** [dmatteo/jsdomify#40]
I recently read your amazing article here:

https://medium.com/podio-engineering-blog/from-karma-to-mocha-with-a-taste-of-jsdom-c9c703a06b21

and then went further digging and found this:

https://medium.com/@bruderstein/the-missing-piece-to-the-react-testing-puzzle-c51cd30df7a0

And they appear to be using JSOM directly (which I know is a dependency of jsdomify) + unexpected. 

What's the difference between the 2 setups? Pros/Cons??

**Comment by dmatteo** [comment]
Hey @faceyspacey, I'm glad you liked my article.

Dave Brotherstone with `unexpected-react` is approaching the testing problem from a "clean slate" point of view, where it makes a lot of sense to use React's shallowRendering every time you can, since it's fast and it's not dragging all the dependencies of your components around.

However we at Podio didn't have the same starting conditions, so we couldn't use the shallowRendering without huge refactoring efforts. Also, it wasn't even there when we started...

<hr>

Back to your question now, what's the difference between using `jsdom` directly and `jsdomify`.  

It's mostly a matter of ease of use, as `jsdomify` helps you deal with creating, resetting and destroy your DOM instance to ensure isolation between test, instead of you having to do all the work.
I also try to ensure that the caching done by Node is not leaking jsdom documents from one instance to the other, which in the React use case can cause a "[Wrong DOM exception](https://github.com/mochajs/mocha/issues/1722)"  

If you use `jsdom` "raw" you basically have to handle all of this yourself :smile: 

Hope I've answer your question thoroughly!

**Comment by dmatteo** [comment]
I'll close this, but feel free to ask any more questions you might have
